### ISSUE TITLE
Final dataset contains 12,475 pairs

### ISSUE THREAD

**Issue by zhaochaocs** [manestay/novel-chapter-dataset#3]
Hi Bryan,

Thanks for making this code public! 

I'm trying to reproduce the dataset and notice that the final dataset contains 12,475 chapter-summary pairs, which is the same as the number of valid ids in `pair_ids_expected.json`. However, it is different from the numbers that were reported in the paper (9,560 before filtering or 8,088 after filtering). I'm wondering if there are any other filtering strategies that should be applied to the dataset?

Thanks for your reply in advance.

**Comment by manestay** [comment]
Hi @zhaochaocs , I am glad you were able to validate all the pair ids. We weren't sure if the scripts would work, 1 year since we last updated them, but looks like you got the exact dataset!

As for the numbers reported in the paper, those are outdated, as we did some additional manual fixes to get more pairs. So 9560 is too little, 127475 is correct.

**Comment by manestay** [comment]
By the way, if you're interested in this task, we are currently running a workshop at COLING 2022. Among the shared tasks are one based on our work (Ladhak et al 20220) and BookSum (Kryściński et al 2022). Note that the dataset for the shared task is different, as it combines parts of both of these datasets. If you're interested, here's the [link](https://creativesumm.github.io/sharedtask), and feel free to email any of the organizers.

**Comment by zhaochaocs** [comment]
Thanks for the clarification, Bryan. Glad to hear that this is the correct version of the dataset. Also, thanks for sharing the information about the workshop with me. Looks quite interesting!
